# Generated by Django 3.2.6 on 2021-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20210828_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(default='USER', max_length=20),
        ),
    ]
